### ISSUE TITLE
GitLab integration with newrelic

### ISSUE THREAD

**Issue by bsddv532** [newrelic-experimental/gitlab#9]
I had configured all the environment variables and also configured the exporters which are mentioned in the blog but still I didn't get any data on my new relic Ui, can anyone help me with this

I followed this blog 
[https://newrelic.com/blog/how-to-relic/monitor-gitlab-with-opentelemetry](url)

![image](https://user-images.githubusercontent.com/90602410/222706387-10ecbf8c-dadb-4c7d-80a3-128745769718.png)

**Comment by dpacheconr** [comment]
Can you send screenshot of the logs from the newrelic-exporters jobs? If it failed to send the data to NR, you should be able to see it in the logs

**Comment by dpacheconr** [comment]
From the output seems job succeeded, but I can't see what version of the exporter was used and seems logs were also 
 disabled, so you should only expect to see span data. Only certain parts of the dashboard will work, as some of them are based on log events from the metrics exporter. Go to query your data in NR and run SELECT * FROM Span WHERE `gitlab.source` = 'gitlab-exporter' since 15 days ago and let us know if you can see any data

**Comment by bsddv532** [comment]
No, I didn't find any data in that query
![image](https://user-images.githubusercontent.com/90602410/223088892-d814fc44-ae13-4d51-a61b-d6924570d8df.png)

**Comment by dpacheconr** [comment]
Have you double checked the account you querying is the same account you set the license key in gitlab?
Feel free to reach out directly via dpacheco@newrelic.com

**Comment by bsddv532** [comment]
Yes this is the same account that I have used

**Comment by dpacheconr** [comment]
Can you show me the variables you configured, your yaml configurations for gitlab.ci, newrelic-exporter, the version exporter you used

**Comment by bsddv532** [comment]
Yeah sure I sent everything in your mail

**Comment by bsddv532** [comment]
Hello Mr. dpacheconr
I tried to integrate GitLab with NewRelic but still I didn't get any data
in new relic


Folder structure:
[image: image.png]

The pipeline which I used is
[image: image.png]


Newrelic exporter
[image: image.png]


Newrelic metrics exporter
[image: image.png]


Environment variables
[image: image.png]




Thanks & Regards
Deepak Kumar Pradhan

**Comment by silanpa** [comment]
I had the same problem, and it was because of the runner setting. If you use the gitlab.com runner, the entrypoint that has the image configured is executed. When you set a local runner depending on the runner configuration is whether the entrypoint of each image is executed. I think that's could be your problem.

**Comment by bsddv532** [comment]
@silanpa are you using a local runner or gitlab.com runner ?

**Comment by silanpa** [comment]
gitlab.com

**Comment by bsddv532** [comment]
I am using local runner, so can you tell me what configurations have to be made to execute the entry point of images.

**Comment by bsddv532** [comment]
No still I didn't get any data in NewRelic

**Comment by silanpa** [comment]
You local runner is a Kubernetes? @bsddv532

**Comment by dpacheconr** [comment]
Have you tried using docker executor runner instead of shell executor runner as per my other email

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bsddv532** [comment]
@dpacheconr 
Yeah, now I got the data in NewRelic, Thank you for the help.

But I think it will be better if this thing is mentioned in the document also that we need to use the docker executor for this integration.
